### ISSUE TITLE
dsc_query fails when a parameter is missing?

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc#121]
I got the following error:

```
dscout <- dscquery(dsc.outdir = "dsc_result",
+                    targets    = c("simulate.scenario","analyze","score.error"))
Running shell command:
dsc-query dsc_result -o /var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T//Rtmp9wTjVT/filec9be68f6843f.csv -f --target simulate.scenario analyze score.error 
INFO: Loading database ...
INFO: Running queries ...
ERROR: Cannot find variable scenario in module sparse
Error in dscquery(dsc.outdir = "dsc_result", targets = c("simulate.scenario",  : 
  dsc-query command failed (returned a non-zero exit status)
```

I have one simulate module with a `scanario` parameter, and another without.
I expected that this would fill in `NA` for the module without that parameter, but
it just crashes...

**Comment by gaow** [comment]
I see, it is a good corner case and I will have to think about query behavior. @stephens999 do you have the code somewhere that I can easily make a minimal working example to reproduce? A lot times reproducing the bug is harder than debugging it. For this case from your comprehensive description I can certainly make one. But would be even easier if it is somewhere on github.

**Comment by gaow** [comment]
Great, get it reproduced with:

```yaml
sim1: R()
  scenario: this
  n: 8
  $out: n

sim2: R()
  n: 9
  $out: n

DSC:
  define:
    scenario: sim1, sim2
```
and 

```
dsc test.dsc --target scenario
```

and 

```r
> dscrutils::dscquery(dsc.outdir = "test", target = "scenario.scenario")
Running shell command:
dsc-query test -o /tmp/RtmpH4RsSm/file1e7923ff6855.csv -f --target scenario.scenario 
INFO: Loading database ...
INFO: Running queries ...
ERROR: Cannot find variable scenario in module sim2
Error in dscrutils::dscquery(dsc.outdir = "test", target = "scenario.scenario") : 
  dsc-query command failed (returned a non-zero exit status)
```

Working on fix now.

**Comment by pcarbo** [comment]
> I expected that this would fill in NA for the module without that parameter.

@stephens999 @gaow I recall we briefly discussed this in a meeting and decided it would be too complicated to implement.

What is the desired behaviour in general? If you run `dsc-query --target x.y`, where `x` is a module name (or module group name) and `y` is a module parameter or module output, should the value always be `NA` if `y` is not defined for a given module? Will it work if `y` is not defined for all modules?

**Comment by pcarbo** [comment]
@gaow How do you decide when the module parameter is NA, and when to report an error? Here you have a simple example of a group, but what about for more complicated examples of module groups? e.g., `winsorized_estimate: winsorize * mean * postprocess1, winsorize * median * postprocess2`. Suppose parameter `x` is defined in `mean` but not `median`?

**Comment by gaow** [comment]
Ahh i see this is where the confusion is: indeed we discussed that for this type of "group" we will not support at all, because it is conceptually not clear, as you pointed out. We are still yet to see if there is a need to break this limitation.

What my patch did was very simple: for "alternating" groups, I'll check for the union of their parameters available, then look into each module in the group, and if the module is missing the parameter I'll just add that parameter and set them all to NA. This is basically along the lines Matthew proposed in his original post.

**Comment by pcarbo** [comment]
@gaow Okay, I think this is better defined now.

**Comment by stephens999** [comment]
just to add that i got around it by adding a parameter "scenario" to the module that did not need it.... which is actually more convenient down the line than having NA!
Maybe a trick to bear in mind for future - a module can have a parameter it does not need
to make queries easier...

**Comment by gaow** [comment]
Again, I take that this issue is fixed but please reopen it otherwise.
