### ISSUE TITLE
Language specific string whitelist

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc#138]
I hoped/thought this would work:

flag: FALSE

but it did not - returned 
Error: object 'False' not found
which is bizarre it changed the upper case to lower case?

would 
flag: "FALSE" work?
It seems to work with 
flag: raw(FALSE)

it would be nice to support boolean flags natively if possible.

**Comment by gaow** [comment]
Okay this is a valid request. We can deal with it more tediously by creating a "white list" for all languages we support. That is, 

- For R, `NULL, NA, NaN, NAN, T, F, TRUE, FALSE` (do we want `T`/`F`?)
- For Python `None, True, False`
- For Shell, ?

This list can grow and please feel free to add comments on what to be included. But it means that once we see these in the corresponding language we automatically protect it from being quoted. Does that sound reasonable?

**Comment by pcarbo** [comment]
@gaow @stephens999 What is wrong with having to do `raw(FALSE)`?

@gaow I thought we weren't supporting `NULL` because it can't be loaded in to a data frame.

**Comment by gaow** [comment]
@pcarbo `NULL` is a special case ... it will have to be converted to `None` if occurred in character, otherwise the query `is null` will not work. And I double we can handle any of your `NA_*` stuff. So there are indeed a lot cases to be made specialized.

I think the idea, if we go for it, is to support a white-list, even if it is partial. That way at least we can clearly tell people clearly what the behavior will be. Of course `raw()` should always work, for the less cared ones.

**Comment by pcarbo** [comment]
@gaow Okay, but why would you support only logical `NA`s, and not numeric `NA`s? My worry is that these are very language specific implementation details that will distract from the overall goal of DSC. And ultimately aren't necessary.

**Comment by gaow** [comment]
Okay I think the bigger picture question is, should we let `raw()` be default behavior? My vote is apparently No because otherwise I'd have not even bothered to make it happen otherwise. 

To be more clear: conceptually, `input: $input`, `parameter: value` and `$output: output` are different, and do not have to be consistent. That is,

1. "input"'s value always starts with `$` to indicate output from another module; 
2. "output"'s value always takes a script variable, that is, `raw()` by default;
3. "parameter"'s value will always add quotes to unquoted string. Any script variables that tries to go into "parameter" must use `raw`. This is to make a clear case between constants (specified strings and numbers) vs. script variables. If we quote strings, it kind of make them stand out from numbers, and unquoted script variables will go un-noticed. This is why I dislike it.

I think this logic is clear. I may have failed to document them well, though.

**Comment by stephens999** [comment]
i want to suggest your reason is actually different: you only index strings
and numbers. So you think of them
as different. The raw indicates you are not indexing by it...

And indexing is also a difference between output and parameters.
(And, incidentally, one might really like to index by TRUE/FALSE...
although maybe one could
do this by using 0/1 instead?)

I'm just saying that the indexing is an issue to be considered.

I'm not sure what i think though on balance. It is pretty natural to me to
quote strings.

**Comment by stephens999** [comment]
actually right now I can't think of any real drawback to "everything gets
passed in as is"
(except pipeline variables). It makes the logic very simple....

indexing is maybe a separate issue.

**Comment by gaow** [comment]
@stephens999 I think you were mostly confused by my failed attempt for "smart" boolean in R, something I recently added because i'm tired of `raw(True)`; yet forgot about R's all caps. If you check out the `master` code now, it is fixed. Actually it is a very simple white-list implementation -- see this line of code

https://github.com/stephenslab/dsc/blob/642f3b1b9dfd8d88bfcda186e77cb3afa2427bce/src/syntax.py#L26

As you can see, `TRUE` `FALSE` and `NULL` are now supported for module parameters. Please feel free to use them in your script. And it is easy to support anything in that white-list. 

`TRUE`, `FALSE` etc in output is always allowed. `TRUE` and `FALSE` in parameter were previously quoted and I do throw a warning message. You did not see it because of the aforementioned bug. Sorry for the inconvenience.

> actually right now I can't think of any real drawback to "everything gets passed in as is"

I can do that, if you still insist after you are now clear about what happens to module parameters, and give the updated version a try. Wouldn't take much time for me to "undo" all the "smartness" in parsing. But I really do like to use `raw()` to emphasize the fact that it is a code chunk, not a regular parameter. 

Or, maybe I'm still insisting because I did not understand your argument about "index"? What do you mean by "index"?

**Comment by gaow** [comment]
> Wouldn't take much time for me to "undo" all the "smartness" in parsing.

Sorry need to take that back: I currently still use a bit of YAML to parse the possibly recursive `key: value` in module parameters, and YAML does not like:

```
n: "a", "b", "c"
```

unless you type in `[]`. So it is:

```
n: ["a", "b", "c"]
```

versus

```
n: a, b, c
```

for parameters. I find the first version unacceptable. So if we quote everything I'll try to hack the YAML class, or write a different parser -- as I said we should not let YAML hold us back if we really decide to change.

**Comment by stephens999** [comment]
I think you are right thant this would not have come up if the error
message had been correct!

However, it seems we both felt raw(TRUE) or raw(True) was unnatural, or at
least a pain.
And now we have got here, I'm
still feeling the simplest solution (from interface perspective) is to pass
everything as is, and have people quote strings.
I think quoting strings is pretty much a universal convention, so it seems
not to be a downside
to me. (I'm not sure why you find them ugly - but you are entitled to your
own aesthetic preferences !)

Most importantly, passing everything as is makes it very easy to reason
about. We can just tell people
`n : xxx`
is equivalent to prepending `n <- xxx` to the module script.
(I'm assuming this is true?)
Or the equivalent in python.

I think it is the "reasoning about" that is key - the white list is
conceptually clear but then you need to keep all
the exceptions in mind, which is a non-trivial burden.

And consistency of behavior of parameters and output, while I agree not
100% required, also reduces
the cognitive burden.

Regarding indexing, I meant when querying output, what kind of query is
allowed.
For example, I believe you allow to subset query on n if n is numeric(?).
But I'm not sure if n is not numeric.
But I now think this is a separate issue.

**Comment by gaow** [comment]
Okay, I think indeed if such behavior has caused even internal confusion it must be addressed to; plus you have made it clear that typings in quote do not feel burdensome. So I will change the behavior to "as us" by default, and update all documentation. I think only Jean will be impacted at this point so I will try to bring her up to speed.

**Comment by gaow** [comment]
And indeed internally i still have to keep the smart data type detection code for what you refer to as indexing, while maintaining an interface that doesn't seen to try do anything smart at the face value. Indeed it is a separate issue. I will think about it before make changes to code. The bottom line is that behavior should be intuitive.

**Comment by gaow** [comment]
@stephens999 @pcarbo implemented the discussion above:

1. Now strings in parameters will have to come with quotes, eg` tag: "eg1", "eg2"`
2. Unquoted string in parameters are default to "raw", that is, we can use `g: c(1/7,1/7)` in an R module, instead of `g: raw(c(1/7,1/7))`
3. The operator `raw()` is not removed and existing scripts with `raw()` would still work. This is not because of backward compatibility support, but because `raw()` is still useful, in situations where a string input as is will mess up the parser, eg: `value: raw(a1,a2,a3), a4, a5, a6`. 
4. Automatic data-type conversion is now restricted to only unquoted integer and float, to ensure basic query features still works on int and float. So `dsc-query` fields should remain intuitive.

Under the hood, we have now officially abandoned the pyYAML parser, after my unsuccessful attempt to hack pyYAML to do what we want. We implemented a new parser. It passes our limited unit tests, but I'm sure it is a lot less robust than pyYAML in handling corner cases. It would be great if you could **update to this version on github `master` and help stress-test it** in your DSC script: please report back errors / confusing error messages whenever you see them, preferably with a minimal example.

I'll later go through the wiki and make changes.

**Comment by gaow** [comment]
@stephens999 I've updated `benchmark.dsc` in `dsc-reg` repo. Please pull before you edit it again.
