### ISSUE TITLE
More powerful `--clean` feature

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#161]
There has been some confusion for the `--clean` option. It currently does two things. I've [updated the documentation](https://stephenslab.github.io/dsc-wiki/reference/Command_Options.html) to (hopefully) explain it better.

`--clean` does not remove any files because I though it is trivial to just `rm -rf /path/to/module/results` but @jdblischak raised the point that it would be convenient to be able to remove groups of modules all at once, if we have an option in `--clean` to do it. I think it is reasonable request. What should the interface be? Currently we have: 

1. `--clean purge`
2. `--clean replace --target ...`

and we add `--clean remove --target ...`? These verbs are all kind of confusing. I am open to interface suggestions.

**Comment by pcarbo** [comment]
@jdblischak Can you give an example where this would be useful? I don't immediately see why you would need to do this.

**Comment by jdblischak** [comment]
> Can you give an example where this would be useful? I don't immediately see why you would need to do this.

@pcarbo Let's say I have a group of seven different analysis methods: `method_one`, `method_two`, etc., and the group name is `methods`. If I have been running my DSC pipeline, then my DSC directory is cluttered with these. If I decide to change the names of every method, then the existing directories will stay in my DSC directory. Before I change the names, I'd like to be able to clean them all up `dsc file.dsc --target methods --clean purge`.

Or another example, let's say that a group of analyses produce a lot of output data and I want to clear up some space. Instead of deleting the entire directory (and thus having to start over next time I run another part of the pipeline), then I could clean just these specific modules by specifying their group.

The manual option is to delete each subdirectory yourself. But for this to be convenient requires decent knowledge of how DSC stores data in its subdirectory, and the names need to be similar enough to use file globbing.

Also, I don't understand the explanation of how to combine `--target` with `--clean`. The docs make it seem like what I want is already possible. What does the below sentence mean?

> 2) When used along with "--clean" it specifies one or more computational modules, separated by space, whose output are to be removed.

**Comment by pcarbo** [comment]
@jdblischak Thanks for these examples. For the first one, it seems that it would be better to run a "clean" operation on *all* files that are no longer relevant (e.g., because the names of some modules have changed). But for the second example I agree it would be useful to specify specific names of modules.

**Comment by jdblischak** [comment]
This isn't that important of a feature to me. My main point is that the sentence

> When used along with "--clean" it specifies one or more computational modules, separated by space, whose output are to be removed.

implies that a user can remove (not replace) the outputs of specific targets. Since this doesn't appear to be currently possible, my recommendation is to either clarify the documentation or enable the described behavior.

**Comment by gaow** [comment]
@jdblischak the help message has been updated. 

> For the first one, it seems that it would be better to run a "clean" operation on all files that are no longer relevant 

That is what `--clean purge` does without `--target`. Currently behavior of `--clean purge --target` is undefined (`--target` is ignored).

Again it is a matter of interface. Seems @jdblischak is already proposing that `--clean purge --target` should simply removes files. And that `--target` should work for module groups. I'm fine with these proposals.

**Comment by jdblischak** [comment]
I think the current behavior now covers my example use cases.

1. How to remove unneeded outputs from renamed modules? Use `--clean purge`
1. How to remove big intermediate files to reduce disk space? Use `--clean replace --target <module>`

So I no longer think any features need to be added or changed. Now it's just a challenge of making sure users are able to quickly determine the correct solution after running `dsc --help`. The recent documentation change clarifying that `--target` can be combined with `--clean purge` (instead of just `--clean`) should help with this.

**Comment by gaow** [comment]
@jdblischak both command interface `dsc -h` and the wiki are up to date now:

https://stephenslab.github.io/dsc-wiki/reference/Command_Options.html

You can pull the current `master` and install it via `pip install .`, or wait for the next release. I'm closing this ticket now.
