### ISSUE TITLE
Output only requested targets in dscquery and dsc-query

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc#180]
@gaow Matthew is recommending that the only columns in the dscquery output are the targets that are specifically requested; in other words, no additional columns are given for module, module group or pathname unless one is specifically requested. I tend to agree that this would make the querying interface more user-friendly. (Further, _all_ targets that are requested should be outputted; in some cases, a target is requested but not output, and no error is generated.)

So we just need to come up with a reasonable syntax for how to request a file. In R, we could simply add an argument such as output.files` which takes names of modules or module groups. And then the column names could be of the form `module.output.file` or `modulegroup.output.file` just as we have it already. You could also have a corresponding `--output-files` or `--results-files` option in dsc-query.

**Comment by gaow** [comment]
This is related to my proposal here:

https://github.com/stephenslab/dsc/issues/179#issuecomment-483302286

(as well as Matthew's separate suggestion on slack)

To recap these two tickets: 

1. When a module or module group is asked for without output variable, we should just populate that column with module names under the group. When it is just a module possibly we have a column of identical module names.
2. We add some syntax to specifically output file names, along the lines @pcarbo suggests above. We can then remove `omit.filenames` option
3. We need an easy way to load any module output along any specified pipeline instance.

Questions: for 1 above do you think this behavior is Okay? and for 3 what's the proposed interface -- by allowing for some option to load all output, combined with `condition`, to `dscquery`, or have a separate function for it? I'm brining it up now because the former solution would be best considered now that we are adding very relevant interface to `dscquery`

**Comment by pcarbo** [comment]
> For 1 above, do you think this behavior is okay? 

Yes, that's exactly it.

> We need an easy way to load any module output along any specified pipeline instance.

I will create a separate ticket for this.

**Comment by gaow** [comment]
Discussions are converging at #182 we'll follow it through in that ticket.
