### ISSUE TITLE
SuSiE Toy example Fatal Python error

### ISSUE THREAD

**Issue by ZacZZZ** [stephenslab/dsc#206]
Dear Stephenslab,

I ran into error from running the toy example from your [susieR repo](https://stephenslab.github.io/susie-paper/finemapping_benchmark.html)
`dsc susie.dsc --target run_comparison -o toy_comparison -c 8`
Below is the error

> INFO: Load command line DSC sequence: run_comparison
> INFO: Checking R library abind ...
> INFO: Checking R library dplyr ...
> INFO: Checking R library magrittr ...
> INFO: Checking R library susieR@stephenslab/susieR ...
> INFO: Checking R library susieR ...
> INFO: Checking R library ggplot2 ...
> INFO: Checking R library cowplot ...
> INFO: Checking Python Module seaborn ...
> INFO: Checking Python Module matplotlib ...
> INFO: Checking Python Module pprint ...
> INFO: DSC script exported to toy_comparison.html
> INFO: Constructing DSC from susie.dsc ...
> INFO: Building DSC database ...
> INFO: Building execution graph & running DSC ...
> [####Fatal Python error: Cannot recover from stack overflow.
> 
> Current thread 0x00007fd86df3f700 (most recent call first):
>   File "/path/to/anaconda3/lib/python3.7/site-packages/sos/targets.py", line 191 in __getattr__
>   File "/path/to/anaconda3/lib/python3.7/site-packages/sos/targets.py", line 191 in __getattr__
>   ... 

From the "..." it just keep repeating the last line.

I think it refers the function in your targets.py of sos
```
    def __getattr__(self, name):
        try:
            return self._dict[name]
        except:
            # if name in self._dict:
            # return self._dict.get(name)
            raise AttributeError(
                f'{self.__class__.__name__} object has no attribute {name}')
```

Any suggestion?

**Comment by gaow** [comment]
Looks like this problem was resolved given what you get in #207 ? I've never seen it and cannot reproduce.

**Comment by pcarbo** [comment]
@gaow If this is an issue specific to the `stephenslab/susie-paper` repository, can we move the issue there?

**Comment by gaow** [comment]
@pcarbo  other issues from the past few days are generic DSC issues not related to `susie-paper`. They are not even that relevant to DSC software itself as DSC was able to properly capture those user errors and prompt them on the screen -- although we might work on improving those prompts.

This issue is more peculiar though:

```
Fatal Python error: Cannot recover from stack overflow.
```

The error message is definitely not informative. But I have never ran into this error before. Also @ZacZZZ , who initially reported the error, seems to have overcome it (potentially by changing some settings on their end). @ZacZZZ it would be great if you could share what you did that you know for fixing this problem. I'm closing this ticket for now.
