### ISSUE TITLE
ERROR: Required Python Module rpy2>=3.0.1 is not available or obsolete. Please install it and try again.

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc#217]
I get this error when trying to run dsc after it has been installed.

**Comment by pcarbo** [comment]
After having upgraded rpy2, I now get this error:

```
INFO: Checking Python Module seaborn ...
ERROR: Required Python Module seaborn is not available or obsolete. Please install it and try again.
```

**Comment by pcarbo** [comment]
Once I upgraded rpy2 and installed seaborn, dsc worked.

**Comment by gaow** [comment]
Thanks @pcarbo would you share with us what commands you used to install the packages? I would not consider it a bug as you labelled, though. It is a feature -- when there is a missing package, instead of trying to automatically install dependencies we ask users to work on it themselves. For example `seaborn` is not a DSC requirement, but rather it is used in some modules in the user's benchmark and was declared in the DSC script. So DSC will check for availability of that package and quit with a prompt to install if it does not find it.

**Comment by pcarbo** [comment]
> For example seaborn is not a DSC requirement, but rather it is used in some modules in the user's benchmark and was declared in the DSC script.

@gaow I see, I didn't realize that seaborn is not used by dsc itself. And is this the same for rpy2?

**Comment by gaow** [comment]
> And is this the same for rpy2?

That is not the case, though. Whenever DSC sees a mixture of Python and R modules, it will check for `ryp2` to ensure files can be communicated between these modules. In our next version we'll work on the data-bus to support more languages so this requirement will be removed down the road. But not until then.

**Comment by pcarbo** [comment]
Perhaps the error messages could be more informative, but doesn't seem critical at the moment, so feel free to close this issue.
